"""empty message

Revision ID: 1c232127d411
Revises: 
Create Date: 2021-06-05 22:35:08.869911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c232127d411'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estadisticas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operador', sa.String(length=100), nullable=False),
    sa.Column('fecha', sa.String(length=20), nullable=False),
    sa.Column('grupo', sa.String(length=100), nullable=False),
    sa.Column('kilometraje', sa.Integer(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estadisticas')
    # ### end Alembic commands ###
